# Solving System of Linear Equations with 3 variables



In this lab we will:

- Use `NumPy` linear algebra package to solve a system of linear equations
- Perform row transformation operations to bring a matrix into row echelon form
- Find the solution for the system of linear equations using the row echolon form of the matrix

## Packages

Load the `NumPy` *library* into memory

In [2]:
import numpy as np

<a name='1'></a>
## 1 - Representing and Solving a System of Linear Equations using Matrices

<a name='1.1'></a>
### 1.1 - System of Linear Equations

Here is a **system of linear equations** with three equations and three unknown variables:


$$\begin{cases}
x+\ \ y+3z=15 \\ x + 2y + 4z = 21 \\ x + \ \ y+ 2z = 13 \end{cases}\tag{1}$$

**To solve** this system of linear equations means to find values of $x$, $y$, $z$ that satisfy all of its equations simultaneously.

<a name='1.2'></a>
### 1.2 - Solving Systems of Linear Equations using Matrices

Create a a 2-D numpy array $A$ which will be a matrix where each row will represent one equation in the system, and $b$ which must be a 1-D array of the right side coefficients:

In [ ]:
A = np.array([
        [1, 1, 3],
        [1, 2, 4],
        [1, 1, 2]
    ])

b = np.array([15, 21, 13])


Print the dimentions of $A$ and $b$ using `shape()` method of `NumPy`.



In [ ]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of b: {np.shape(b)}")

Shape of A: (3, 3)
Shape of b: (3,)


Solve the equaiton $Ax=b$ using `np.linalg.solve(A, b)`. The result will be saved in the 1-D array $s$. The elements will correspond to the values of $x$, $y$ and $z$:

In [ ]:
s = np.linalg.solve(A,b)

print(f"Solution: {s}")

Solution: [5. 4. 2.]


<a name='2'></a>
## 2 - Solving System of Linear Equations using Row Reduction

<a name='2.1'></a>
### 2.1 - Preparation for Row Reduction


Firstly, we need to create an augmented matrix $A$_$system$  by unify  matrix $A$ and array $b$ into one matrix using the `np.hstack()` function.


In [13]:
A_system = np.hstack((A, b.reshape(3,1)))

print(A_system)

[[ 1  1  3 15]
 [ 1  2  4 21]
 [ 1  1  2 13]]


<a name='2.2'></a>

### 2.2 - Elementary Row Operations
While solving a system of linear equations, we are allowed to performed these row transformation operations:

1.   Multiply one row by a non-zero number
2.   Replace one row with the sum of that row with another row.
3.   Exchange two rows.


Next, we will define one Python function for each of the opeations mentioned above:

In [ ]:
#row = scalar * row
def MultiplyRow(M, row, scalar):
    None

In [ ]:
# row_num_2 = scalar * row_num_1 + row_num_2,
def AddRows(M, row_num_1, row_num_2, scalar):
    None

In [ ]:
# exchange row_num_1 and row_num_2 of the matrix M
def ExchangeRows(M, row_num_1, row_num_2):
    None

<a name='2.3'></a>


### 2.3 - Row Echelon Form
Provide all steps to convert Matrix $A$_$system$ into row echelon form.

- Row_2 = Row_2 - Row_1

In [ ]:
A_ref = None
print(A_ref)

- Row_3  = Row_3 - Row_1

In [ ]:
A_ref = None
print(A_ref)

- Row_3 = -1 * Row_3

In [ ]:
A_ref = None
print(A_ref)

Now, it is easy to find the value of z is 2 from the third row. Moving upward by substritution we can find teh value of y is 4 and value of x is 5.  


In [ ]:
z = None
y = None
x = None

print(x, y, z)

<a name='2.4'></a>


### 2.4 - Reduced Row Echelon Form

Let us continue our row operations to convert the matrix into reduced row echelon form.

- Row_2  = Row_2 - Row_3

In [ ]:
A_rref = None
print(A_rref)

Row_1 = Row_1 - 3*Row_3

In [ ]:
A_rref = None
print(A_rref)

Row_1 = Row_1 - Row_2

In [ ]:
A_rref = None
print(A_rref)

Once, the matrix has reached reduced row echelon form, it is trivial to see that: \\
$$x = 5 \\
y = 4 \\
z=2$$

<a name='3'></a>
## 3 - Computing the inverse of matrices using Row Reduction

In [ ]:
print("Matrix A: ")
print(A)

In [ ]:
det = None
print(f"Determinant of A: {det}")

Firstly, we need to create an augmented matrix by unifying matrix A with a 3x3 identity matrix using using the `np.hstack()` function.

In [ ]:
A_aug = None
print("The augmented matrix is: ")
print(A_aug)

Apply all row transformations to convert the left 3 by 3 matrix to the identity matrix.

In [ ]:
None

In [ ]:
A_aug

In [ ]:
A_inv = None

In [ ]:
A_inv

Make sure to check whether A time A_inv gives the identity matrix:

In [ ]:
A.dot(A_inv)

There is an easier way to compute the inverse of a matrix by using `np.linalg.inv` function.

In [ ]:
None